### ISSUE TITLE
input file removed

### ISSUE THREAD

**Issue by martin-mann** [PatrickRWright/CopraRNA#16]
the current version removes the input files "input_sRNA.fa" on completion, which breaks the webserver's restart workflow..

I added an according commit to the dev branch 27383eff828d56671de0d51dcd33670f158c6625 which fixes the problem.

I checked whether there is a nicer way, but unfortunately, the input variable with the original file name gets overwritten... uaks.. and I dont want to work around all this. no need anyway.

@eggzilla could you please release a new version and push it to bioconda?  thanks!

**Comment by eggzilla** [comment]
hey, i will get (w)right on it :-)

**Comment by martin-mann** [comment]
muhaha.. you are a star.. but no need for a rush. Have tweaked the version on the webserver already..

**Comment by eggzilla** [comment]
Ok, pull-request ist raus https://github.com/bioconda/bioconda-recipes/pull/7828

**Comment by eggzilla** [comment]
Done, Bjoern has merged it. Schliess das issue bitte wenn du zufrieden bist :-D

**Comment by martin-mann** [comment]
wie immer sehrst zufrieden! many danke und überhaupt!
