### ISSUE TITLE
domclust crashes ...

### ISSUE THREAD

**Issue by martin-raden** [PatrickRWright/CopraRNA#26]
Hi @PatrickRWright ,
did you ever face domclust crashes? I get some jobs where domclust aborts and writes a loooong list to STDERR..

Investigating successful jobs, 
```[bash]
-bash-4.1$ wc -l all*
   26782 all.fas
  216468 all.fas.blast
   13391 all.fas.gene
  108088 all.fas.hom
    4449 all.fas.phr
    1209 all.fas.pin
  180337 all.fas.psq
   13391 all.fas.tit
```
the (failing) domclust input seems to be quite large
```[bash]
   122652 all.fas
  5083717 all.fas.blast
    61326 all.fas.gene
  2384068 all.fas.hom
      496 all.fas.phr
     2158 all.fas.pin
  1038336 all.fas.psq
    61326 all.fas.tit
```

any idea? suggestion?

**Comment by PatrickRWright** [comment]
memory?

**Comment by martin-mann** [comment]
nope... also restarting the domclust call without restrictions causes the crash...
seems I will have to debug domclust.. :/

**Comment by martin-raden** [comment]
maybe this relates to #35
